name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install QBE
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        git clone https://c9x.me/git/qbe.git
        cd qbe
        sudo make install

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: TMPDIR=${{ runner.temp }} cargo test --verbose -- --nocapture

