name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install QBE
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        git clone git://c9x.me/qbe.git
        cd qbe
        sudo make install

    - name: Run tests
      run: cargo test --verbose

    - name: Adding x86_64 musl target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Adding aarch64 musl target
      run: rustup target add aarch64-unknown-linux-musl

    - name: Build Debug x86
      run: cargo build --target=x86_64-unknown-linux-musl --verbose

    - name: Build Release x86
      run: cargo build --target=x86_64-unknown-linux-musl --release --verbose

    - name: Build Debug aarch64
      run: cargo build --target=aarch64-unknown-linux-musl --verbose

    - name: Build Release aarch64
      run: cargo build --target=aarch64-unknown-linux-musl --release --verbose

    - name: Upload Debug x86 build
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: black-debug
        path: target/x86_64-unknown-linux-musl/debug/black

    - name: Upload Release x86 build
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: black
        path: target/x86_64-unknown-linux-musl/release/black

    - name: Upload Debug aarch64 build
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: black-arm-debug
        path: target/aarch64-unknown-linux-musl/debug/black

    - name: Upload Release aarch64 build
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: black-arm
        path: target/aarch64-unknown-linux-musl/release/black

