name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install QBE
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        git clone git://c9x.me/qbe.git
        cd qbe
        sudo make install

    - name: Build Debug
      run: cargo build --verbose

    - name: Build Release
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Upload binary artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: black-binary
        path: target/release/black

