name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install QBE
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        git clone git://c9x.me/qbe.git
        cd qbe
        sudo make install

    - name: Adding musl target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build Debug
      run: cargo build --target=x86_64-unknown-linux-musl --verbose

    - name: Build Release
      run: cargo build --target=x86_64-unknown-linux-musl --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Upload debug build
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: black-debug
        path: target/x86_64-unknown-linux-musl/debug/black

    - name: Upload release build
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: black
        path: target/x86_64-unknown-linux-musl/release/black

